export interface StockInfo {
  symbol: string
  name: string
  exchange: string
}

export const STOCK_SYMBOLS: StockInfo[] = [
  // S&P 500 - Top 250
  { symbol: "AAPL", name: "Apple Inc.", exchange: "NASDAQ" },
  { symbol: "MSFT", name: "Microsoft Corporation", exchange: "NASDAQ" },
  { symbol: "GOOGL", name: "Alphabet Inc.", exchange: "NASDAQ" },
  { symbol: "AMZN", name: "Amazon.com Inc.", exchange: "NASDAQ" },
  { symbol: "NVDA", name: "NVIDIA Corporation", exchange: "NASDAQ" },
  { symbol: "META", name: "Meta Platforms Inc.", exchange: "NASDAQ" },
  { symbol: "TSLA", name: "Tesla Inc.", exchange: "NASDAQ" },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc.", exchange: "NYSE" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", exchange: "NYSE" },
  { symbol: "V", name: "Visa Inc.", exchange: "NYSE" },
  { symbol: "JNJ", name: "Johnson & Johnson", exchange: "NYSE" },
  { symbol: "WMT", name: "Walmart Inc.", exchange: "NYSE" },
  { symbol: "MA", name: "Mastercard Inc.", exchange: "NYSE" },
  { symbol: "PG", name: "Procter & Gamble Co.", exchange: "NYSE" },
  { symbol: "DIS", name: "The Walt Disney Company", exchange: "NYSE" },
  { symbol: "HD", name: "The Home Depot Inc.", exchange: "NYSE" },
  { symbol: "BAC", name: "Bank of America Corp.", exchange: "NYSE" },
  { symbol: "XOM", name: "Exxon Mobil Corp.", exchange: "NYSE" },
  { symbol: "CSCO", name: "Cisco Systems Inc.", exchange: "NASDAQ" },
  { symbol: "PFE", name: "Pfizer Inc.", exchange: "NYSE" },
  { symbol: "UNH", name: "UnitedHealth Group Inc.", exchange: "NYSE" },
  { symbol: "ABBV", name: "AbbVie Inc.", exchange: "NYSE" },
  { symbol: "ABT", name: "Abbott Laboratories", exchange: "NYSE" },
  { symbol: "CVX", name: "Chevron Corp.", exchange: "NYSE" },
  { symbol: "KO", name: "The Coca-Cola Co.", exchange: "NYSE" },
  { symbol: "PEP", name: "PepsiCo Inc.", exchange: "NASDAQ" },
  { symbol: "MRK", name: "Merck & Co. Inc.", exchange: "NYSE" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc.", exchange: "NYSE" },
  { symbol: "AVGO", name: "Broadcom Inc.", exchange: "NASDAQ" },
  { symbol: "COST", name: "Costco Wholesale Corp.", exchange: "NASDAQ" },
  { symbol: "ADBE", name: "Adobe Inc.", exchange: "NASDAQ" },
  { symbol: "CRM", name: "Salesforce Inc.", exchange: "NYSE" },
  { symbol: "NFLX", name: "Netflix Inc.", exchange: "NASDAQ" },
  { symbol: "CMCSA", name: "Comcast Corp.", exchange: "NASDAQ" },
  { symbol: "PYPL", name: "PayPal Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "INTC", name: "Intel Corp.", exchange: "NASDAQ" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", exchange: "NASDAQ" },
  { symbol: "QCOM", name: "Qualcomm Inc.", exchange: "NASDAQ" },
  { symbol: "TXN", name: "Texas Instruments Inc.", exchange: "NASDAQ" },
  { symbol: "IBM", name: "International Business Machines Corp.", exchange: "NYSE" },
  { symbol: "BA", name: "The Boeing Co.", exchange: "NYSE" },
  { symbol: "NKE", name: "Nike Inc.", exchange: "NYSE" },
  { symbol: "WFC", name: "Wells Fargo & Co.", exchange: "NYSE" },
  { symbol: "C", name: "Citigroup Inc.", exchange: "NYSE" },
  { symbol: "GS", name: "The Goldman Sachs Group Inc.", exchange: "NYSE" },
  { symbol: "MS", name: "Morgan Stanley", exchange: "NYSE" },
  { symbol: "ORCL", name: "Oracle Corp.", exchange: "NYSE" },
  { symbol: "HON", name: "Honeywell International Inc.", exchange: "NASDAQ" },
  { symbol: "UPS", name: "United Parcel Service Inc.", exchange: "NYSE" },
  { symbol: "MCD", name: "McDonald's Corp.", exchange: "NYSE" },
  { symbol: "SBUX", name: "Starbucks Corp.", exchange: "NASDAQ" },
  { symbol: "LOW", name: "Lowe's Companies Inc.", exchange: "NYSE" },
  { symbol: "MMM", name: "3M Co.", exchange: "NYSE" },
  { symbol: "CAT", name: "Caterpillar Inc.", exchange: "NYSE" },
  { symbol: "AXP", name: "American Express Co.", exchange: "NYSE" },
  { symbol: "GE", name: "General Electric Co.", exchange: "NYSE" },
  { symbol: "AMAT", name: "Applied Materials Inc.", exchange: "NASDAQ" },
  { symbol: "BKNG", name: "Booking Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "ISRG", name: "Intuitive Surgical Inc.", exchange: "NASDAQ" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "AMGN", name: "Amgen Inc.", exchange: "NASDAQ" },
  { symbol: "ADI", name: "Analog Devices Inc.", exchange: "NASDAQ" },
  { symbol: "MU", name: "Micron Technology Inc.", exchange: "NASDAQ" },
  { symbol: "LRCX", name: "Lam Research Corp.", exchange: "NASDAQ" },
  { symbol: "KLAC", name: "KLA Corp.", exchange: "NASDAQ" },
  { symbol: "ASML", name: "ASML Holding N.V.", exchange: "NASDAQ" },
  { symbol: "TMUS", name: "T-Mobile US Inc.", exchange: "NASDAQ" },
  { symbol: "T", name: "AT&T Inc.", exchange: "NYSE" },
  { symbol: "VZ", name: "Verizon Communications Inc.", exchange: "NYSE" },
  { symbol: "DHR", name: "Danaher Corp.", exchange: "NYSE" },
  { symbol: "MDT", name: "Medtronic PLC", exchange: "NYSE" },
  { symbol: "SYK", name: "Stryker Corp.", exchange: "NYSE" },
  { symbol: "BSX", name: "Boston Scientific Corp.", exchange: "NYSE" },
  { symbol: "SPGI", name: "S&P Global Inc.", exchange: "NYSE" },
  { symbol: "PLD", name: "Prologis Inc.", exchange: "NYSE" },
  { symbol: "AMT", name: "American Tower Corp.", exchange: "NYSE" },
  { symbol: "CCI", name: "Crown Castle Inc.", exchange: "NYSE" },
  { symbol: "DE", name: "Deere & Co.", exchange: "NYSE" },
  { symbol: "NEE", name: "NextEra Energy Inc.", exchange: "NYSE" },
  { symbol: "DUK", name: "Duke Energy Corp.", exchange: "NYSE" },
  { symbol: "SO", name: "The Southern Co.", exchange: "NYSE" },
  { symbol: "COP", name: "ConocoPhillips", exchange: "NYSE" },
  { symbol: "SLB", name: "Schlumberger N.V.", exchange: "NYSE" },
  { symbol: "LMT", name: "Lockheed Martin Corp.", exchange: "NYSE" },
  { symbol: "RTX", name: "RTX Corp.", exchange: "NYSE" },
  { symbol: "GD", name: "General Dynamics Corp.", exchange: "NYSE" },
  { symbol: "NOC", name: "Northrop Grumman Corp.", exchange: "NYSE" },
  { symbol: "MO", name: "Altria Group Inc.", exchange: "NYSE" },
  { symbol: "PM", name: "Philip Morris International Inc.", exchange: "NYSE" },
  { symbol: "CL", name: "Colgate-Palmolive Co.", exchange: "NYSE" },
  { symbol: "EL", name: "The Estee Lauder Companies Inc.", exchange: "NYSE" },
  { symbol: "TJX", name: "The TJX Companies Inc.", exchange: "NYSE" },
  { symbol: "TGT", name: "Target Corp.", exchange: "NYSE" },
  { symbol: "FDX", name: "FedEx Corp.", exchange: "NYSE" },
  { symbol: "CHTR", name: "Charter Communications Inc.", exchange: "NASDAQ" },
  { symbol: "EQIX", name: "Equinix Inc.", exchange: "NYSE" },
  { symbol: "ICE", name: "Intercontinental Exchange Inc.", exchange: "NYSE" },
  { symbol: "CME", name: "CME Group Inc.", exchange: "NASDAQ" },
  { symbol: "MMC", name: "Marsh & McLennan Companies Inc.", exchange: "NYSE" },
  { symbol: "AON", name: "Aon PLC", exchange: "NYSE" },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co.", exchange: "NYSE" },
  { symbol: "CB", name: "Chubb Ltd.", exchange: "NYSE" },
  { symbol: "MET", name: "MetLife Inc.", exchange: "NYSE" },
  { symbol: "PRU", name: "Prudential Financial Inc.", exchange: "NYSE" },
  { symbol: "AIG", name: "American International Group Inc.", exchange: "NYSE" },
  { symbol: "USB", name: "U.S. Bancorp", exchange: "NYSE" },
  { symbol: "PNC", name: "The PNC Financial Services Group Inc.", exchange: "NYSE" },
  { symbol: "TFC", name: "Truist Financial Corp.", exchange: "NYSE" },
  { symbol: "COF", name: "Capital One Financial Corp.", exchange: "NYSE" },
  { symbol: "BLK", name: "BlackRock Inc.", exchange: "NYSE" },
  { symbol: "FISV", name: "Fiserv Inc.", exchange: "NYSE" },
  { symbol: "FIS", name: "Fidelity National Information Services Inc.", exchange: "NYSE" },
  { symbol: "SQ", name: "Block Inc.", exchange: "NYSE" },
  { symbol: "INTU", name: "Intuit Inc.", exchange: "NASDAQ" },
  { symbol: "NOW", name: "ServiceNow Inc.", exchange: "NYSE" },
  { symbol: "UBER", name: "Uber Technologies Inc.", exchange: "NYSE" },
  { symbol: "LYFT", name: "Lyft Inc.", exchange: "NASDAQ" },
  { symbol: "SNAP", name: "Snap Inc.", exchange: "NYSE" },
  { symbol: "PINS", name: "Pinterest Inc.", exchange: "NYSE" },
  { symbol: "DDOG", name: "Datadog Inc.", exchange: "NASDAQ" },
  { symbol: "CRWD", name: "CrowdStrike Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "ZS", name: "Zscaler Inc.", exchange: "NASDAQ" },
  { symbol: "PANW", name: "Palo Alto Networks Inc.", exchange: "NASDAQ" },
  { symbol: "FTNT", name: "Fortinet Inc.", exchange: "NASDAQ" },
  { symbol: "CHKP", name: "Check Point Software Technologies Ltd.", exchange: "NASDAQ" },
  { symbol: "OKTA", name: "Okta Inc.", exchange: "NASDAQ" },
  { symbol: "WDAY", name: "Workday Inc.", exchange: "NASDAQ" },
  { symbol: "ADSK", name: "Autodesk Inc.", exchange: "NASDAQ" },
  { symbol: "ANSS", name: "ANSYS Inc.", exchange: "NASDAQ" },
  { symbol: "CDNS", name: "Cadence Design Systems Inc.", exchange: "NASDAQ" },
  { symbol: "SNPS", name: "Synopsys Inc.", exchange: "NASDAQ" },
  { symbol: "ROP", name: "Roper Technologies Inc.", exchange: "NYSE" },
  { symbol: "APH", name: "Amphenol Corp.", exchange: "NYSE" },
  { symbol: "EMR", name: "Emerson Electric Co.", exchange: "NYSE" },
  { symbol: "ETN", name: "Eaton Corp. PLC", exchange: "NYSE" },
  { symbol: "PH", name: "Parker-Hannifin Corp.", exchange: "NYSE" },
  { symbol: "ITW", name: "Illinois Tool Works Inc.", exchange: "NYSE" },
  { symbol: "PPG", name: "PPG Industries Inc.", exchange: "NYSE" },
  { symbol: "SHW", name: "The Sherwin-Williams Co.", exchange: "NYSE" },
  { symbol: "ECL", name: "Ecolab Inc.", exchange: "NYSE" },
  { symbol: "WM", name: "Waste Management Inc.", exchange: "NYSE" },
  { symbol: "RSG", name: "Republic Services Inc.", exchange: "NYSE" },
  { symbol: "WMB", name: "The Williams Companies Inc.", exchange: "NYSE" },
  { symbol: "OKE", name: "ONEOK Inc.", exchange: "NYSE" },
  { symbol: "KMI", name: "Kinder Morgan Inc.", exchange: "NYSE" },
  { symbol: "SRE", name: "Sempra", exchange: "NYSE" },
  { symbol: "AEP", name: "American Electric Power Co. Inc.", exchange: "NASDAQ" },
  { symbol: "EXC", name: "Exelon Corp.", exchange: "NASDAQ" },
  { symbol: "PEG", name: "Public Service Enterprise Group Inc.", exchange: "NYSE" },
  { symbol: "XEL", name: "Xcel Energy Inc.", exchange: "NASDAQ" },
  { symbol: "ED", name: "Consolidated Edison Inc.", exchange: "NYSE" },
  { symbol: "EIX", name: "Edison International", exchange: "NYSE" },
  { symbol: "PCG", name: "PG&E Corp.", exchange: "NYSE" },
  { symbol: "D", name: "Dominion Energy Inc.", exchange: "NYSE" },
  { symbol: "ATO", name: "Atmos Energy Corp.", exchange: "NYSE" },
  { symbol: "AWK", name: "American Water Works Co. Inc.", exchange: "NYSE" },
  { symbol: "SBAC", name: "SBA Communications Corp.", exchange: "NASDAQ" },
  { symbol: "TEL", name: "TE Connectivity Ltd.", exchange: "NYSE" },
  { symbol: "GLW", name: "Corning Inc.", exchange: "NYSE" },
  { symbol: "GPN", name: "Global Payments Inc.", exchange: "NYSE" },
  { symbol: "EW", name: "Edwards Lifesciences Corp.", exchange: "NYSE" },
  { symbol: "BDX", name: "Becton Dickinson and Co.", exchange: "NYSE" },
  { symbol: "ZTS", name: "Zoetis Inc.", exchange: "NYSE" },
  { symbol: "ILMN", name: "Illumina Inc.", exchange: "NASDAQ" },
  { symbol: "BIIB", name: "Biogen Inc.", exchange: "NASDAQ" },
  { symbol: "GILD", name: "Gilead Sciences Inc.", exchange: "NASDAQ" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "MRNA", name: "Moderna Inc.", exchange: "NASDAQ" },
  { symbol: "BNTX", name: "BioNTech SE", exchange: "NASDAQ" },
  { symbol: "SGEN", name: "Seagen Inc.", exchange: "NASDAQ" },
  { symbol: "ALGN", name: "Align Technology Inc.", exchange: "NASDAQ" },
  { symbol: "DXCM", name: "Dexcom Inc.", exchange: "NASDAQ" },
  { symbol: "PODD", name: "Insulet Corp.", exchange: "NASDAQ" },
  { symbol: "IDXX", name: "IDEXX Laboratories Inc.", exchange: "NASDAQ" },
  { symbol: "WST", name: "West Pharmaceutical Services Inc.", exchange: "NYSE" },
  { symbol: "MTD", name: "Mettler-Toledo International Inc.", exchange: "NYSE" },
  { symbol: "WAT", name: "Waters Corp.", exchange: "NYSE" },
  { symbol: "LHX", name: "L3Harris Technologies Inc.", exchange: "NYSE" },
  { symbol: "HWM", name: "Howmet Aerospace Inc.", exchange: "NYSE" },
  { symbol: "GEHC", name: "GE HealthCare Technologies Inc.", exchange: "NASDAQ" },
  { symbol: "SOLV", name: "Solventum Corp.", exchange: "NYSE" },
  { symbol: "VTRS", name: "Viatris Inc.", exchange: "NASDAQ" },
  { symbol: "OXY", name: "Occidental Petroleum Corp.", exchange: "NYSE" },
  { symbol: "DVN", name: "Devon Energy Corp.", exchange: "NYSE" },
  { symbol: "HES", name: "Hess Corp.", exchange: "NYSE" },
  { symbol: "MPC", name: "Marathon Petroleum Corp.", exchange: "NYSE" },
  { symbol: "PSX", name: "Phillips 66", exchange: "NYSE" },
  { symbol: "VLO", name: "Valero Energy Corp.", exchange: "NYSE" },
  { symbol: "EOG", name: "EOG Resources Inc.", exchange: "NYSE" },
  { symbol: "PXD", name: "Pioneer Natural Resources Co.", exchange: "NYSE" },
  { symbol: "HAL", name: "Halliburton Co.", exchange: "NYSE" },
  { symbol: "BKR", name: "Baker Hughes Co.", exchange: "NASDAQ" },
  { symbol: "FCX", name: "Freeport-McMoRan Inc.", exchange: "NYSE" },
  { symbol: "NEM", name: "Newmont Corp.", exchange: "NYSE" },
  { symbol: "DOW", name: "Dow Inc.", exchange: "NYSE" },
  { symbol: "LYB", name: "LyondellBasell Industries N.V.", exchange: "NYSE" },
  { symbol: "APD", name: "Air Products and Chemicals Inc.", exchange: "NYSE" },
  { symbol: "LIN", name: "Linde PLC", exchange: "NASDAQ" },
  { symbol: "SHW", name: "The Sherwin-Williams Co.", exchange: "NYSE" },
  { symbol: "CTVA", name: "Corteva Inc.", exchange: "NYSE" },
  { symbol: "FMC", name: "FMC Corp.", exchange: "NYSE" },
  { symbol: "MOS", name: "The Mosaic Co.", exchange: "NYSE" },
  { symbol: "CF", name: "CF Industries Holdings Inc.", exchange: "NYSE" },
  { symbol: "ADM", name: "Archer-Daniels-Midland Co.", exchange: "NYSE" },
  { symbol: "BG", name: "Bunge Global SA", exchange: "NYSE" },
  { symbol: "KHC", name: "The Kraft Heinz Co.", exchange: "NASDAQ" },
  { symbol: "CAG", name: "Conagra Brands Inc.", exchange: "NYSE" },
  { symbol: "CPB", name: "Campbell's Co.", exchange: "NYSE" },
  { symbol: "GIS", name: "General Mills Inc.", exchange: "NYSE" },
  { symbol: "K", name: "Kellanova", exchange: "NYSE" },
  { symbol: "SJM", name: "The J.M. Smucker Co.", exchange: "NYSE" },
  { symbol: "HRL", name: "Hormel Foods Corp.", exchange: "NYSE" },
  { symbol: "TSN", name: "Tyson Foods Inc.", exchange: "NYSE" },
  { symbol: "MDLZ", name: "Mondelez International Inc.", exchange: "NASDAQ" },
  { symbol: "HSY", name: "The Hershey Co.", exchange: "NYSE" },
  { symbol: "STZ", name: "Constellation Brands Inc.", exchange: "NYSE" },
  { symbol: "MNST", name: "Monster Beverage Corp.", exchange: "NASDAQ" },
  { symbol: "KDP", name: "Keurig Dr Pepper Inc.", exchange: "NASDAQ" },
  { symbol: "CCE", name: "Coca-Cola Europacific Partners PLC", exchange: "NASDAQ" },
  { symbol: "WBA", name: "Walgreens Boots Alliance Inc.", exchange: "NASDAQ" },
  { symbol: "CVS", name: "CVS Health Corp.", exchange: "NYSE" },
  { symbol: "MCK", name: "McKesson Corp.", exchange: "NYSE" },
  { symbol: "ABC", name: "AmerisourceBergen Corp.", exchange: "NYSE" },
  { symbol: "CAH", name: "Cardinal Health Inc.", exchange: "NYSE" },
  { symbol: "HUM", name: "Humana Inc.", exchange: "NYSE" },
  { symbol: "CI", name: "The Cigna Group", exchange: "NYSE" },
  { symbol: "CNC", name: "Centene Corp.", exchange: "NYSE" },
  { symbol: "MOH", name: "Molina Healthcare Inc.", exchange: "NYSE" },
  { symbol: "ELV", name: "Elevance Health Inc.", exchange: "NYSE" },
  { symbol: "UNH", name: "UnitedHealth Group Inc.", exchange: "NYSE" },
  { symbol: "HCA", name: "HCA Healthcare Inc.", exchange: "NYSE" },
  { symbol: "DVA", name: "DaVita Inc.", exchange: "NYSE" },
  { symbol: "UHS", name: "Universal Health Services Inc.", exchange: "NYSE" },
  { symbol: "EBAY", name: "eBay Inc.", exchange: "NASDAQ" },
  { symbol: "ETSY", name: "Etsy Inc.", exchange: "NASDAQ" },
  { symbol: "ROST", name: "Ross Stores Inc.", exchange: "NASDAQ" },
  { symbol: "BKNG", name: "Booking Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "EXPE", name: "Expedia Group Inc.", exchange: "NASDAQ" },
  { symbol: "ABNB", name: "Airbnb Inc.", exchange: "NASDAQ" },
  { symbol: "MAR", name: "Marriott International Inc.", exchange: "NASDAQ" },
  { symbol: "HLT", name: "Hilton Worldwide Holdings Inc.", exchange: "NYSE" },
  { symbol: "CCL", name: "Carnival Corp.", exchange: "NYSE" },
  { symbol: "RCL", name: "Royal Caribbean Cruises Ltd.", exchange: "NYSE" },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings Ltd.", exchange: "NYSE" },
  { symbol: "WYNN", name: "Wynn Resorts Ltd.", exchange: "NASDAQ" },
  { symbol: "LVS", name: "Las Vegas Sands Corp.", exchange: "NYSE" },
  { symbol: "MGM", name: "MGM Resorts International", exchange: "NYSE" },
  { symbol: "DAL", name: "Delta Air Lines Inc.", exchange: "NYSE" },
  { symbol: "UAL", name: "United Airlines Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "AAL", name: "American Airlines Group Inc.", exchange: "NASDAQ" },
  { symbol: "LUV", name: "Southwest Airlines Co.", exchange: "NYSE" },
  { symbol: "SAVE", name: "Spirit Airlines Inc.", exchange: "NYSE" },
  { symbol: "ALK", name: "Alaska Air Group Inc.", exchange: "NYSE" },
  { symbol: "JBLU", name: "JetBlue Airways Corp.", exchange: "NASDAQ" },
  { symbol: "SKX", name: "Skechers U.S.A. Inc.", exchange: "NYSE" },
  { symbol: "DECK", name: "Deckers Outdoor Corp.", exchange: "NYSE" },
  { symbol: "TPR", name: "Tapestry Inc.", exchange: "NYSE" },
  { symbol: "RL", name: "Ralph Lauren Corp.", exchange: "NYSE" },
  { symbol: "PVH", name: "PVH Corp.", exchange: "NYSE" },
  { symbol: "VFC", name: "V.F. Corp.", exchange: "NYSE" },
  { symbol: "LEVI", name: "Levi Strauss & Co.", exchange: "NYSE" },
  { symbol: "AEO", name: "American Eagle Outfitters Inc.", exchange: "NYSE" },
  { symbol: "ANF", name: "Abercrombie & Fitch Co.", exchange: "NYSE" },
  { symbol: "URBN", name: "Urban Outfitters Inc.", exchange: "NASDAQ" },
  { symbol: "GPS", name: "The Gap Inc.", exchange: "NYSE" },
  { symbol: "JWN", name: "Nordstrom Inc.", exchange: "NYSE" },
  { symbol: "M", name: "Macy's Inc.", exchange: "NYSE" },
  { symbol: "KSS", name: "Kohl's Corp.", exchange: "NYSE" },
  { symbol: "BBY", name: "Best Buy Co. Inc.", exchange: "NYSE" },
  { symbol: "AMZN", name: "Amazon.com Inc.", exchange: "NASDAQ" },
  { symbol: "WMT", name: "Walmart Inc.", exchange: "NYSE" },
  { symbol: "TGT", name: "Target Corp.", exchange: "NYSE" },
  { symbol: "COST", name: "Costco Wholesale Corp.", exchange: "NASDAQ" },
  { symbol: "DLTR", name: "Dollar Tree Inc.", exchange: "NASDAQ" },
  { symbol: "DG", name: "Dollar General Corp.", exchange: "NYSE" },
  { symbol: "FIVE", name: "Five Below Inc.", exchange: "NASDAQ" },
  { symbol: "DKS", name: "Dick's Sporting Goods Inc.", exchange: "NYSE" },
  { symbol: "FOXA", name: "Fox Corp.", exchange: "NASDAQ" },
  { symbol: "DIS", name: "The Walt Disney Co.", exchange: "NYSE" },
  { symbol: "NFLX", name: "Netflix Inc.", exchange: "NASDAQ" },
  { symbol: "CMCSA", name: "Comcast Corp.", exchange: "NASDAQ" },
  { symbol: "WBD", name: "Warner Bros. Discovery Inc.", exchange: "NASDAQ" },
  { symbol: "PARA", name: "Paramount Global", exchange: "NASDAQ" },
  { symbol: "LYV", name: "Live Nation Entertainment Inc.", exchange: "NYSE" },
  { symbol: "NWSA", name: "News Corp.", exchange: "NASDAQ" },
  { symbol: "NYT", name: "The New York Times Co.", exchange: "NYSE" },
  { symbol: "RBLX", name: "Roblox Corp.", exchange: "NYSE" },
  { symbol: "EA", name: "Electronic Arts Inc.", exchange: "NASDAQ" },
  { symbol: "TTWO", name: "Take-Two Interactive Software Inc.", exchange: "NASDAQ" },
  { symbol: "ATVI", name: "Activision Blizzard Inc.", exchange: "NASDAQ" },
  { symbol: "NTES", name: "NetEase Inc.", exchange: "NASDAQ" },
  { symbol: "SE", name: "Sea Ltd.", exchange: "NYSE" },
  { symbol: "GRAB", name: "Grab Holdings Ltd.", exchange: "NASDAQ" },
  { symbol: "SIRI", name: "Sirius XM Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "SPOT", name: "Spotify Technology S.A.", exchange: "NYSE" },
  { symbol: "ZM", name: "Zoom Communications Inc.", exchange: "NASDAQ" },
  { symbol: "DOCU", name: "DocuSign Inc.", exchange: "NASDAQ" },
  { symbol: "SMAR", name: "Smartsheet Inc.", exchange: "NYSE" },
  { symbol: "TEAM", name: "Atlassian Corp.", exchange: "NASDAQ" },
  { symbol: "TREX", name: "Trex Co. Inc.", exchange: "NYSE" },
  { symbol: "POOL", name: "Pool Corp.", exchange: "NASDAQ" },
  { symbol: "BLD", name: "TopBuild Corp.", exchange: "NYSE" },
  { symbol: "TT", name: "Trane Technologies PLC", exchange: "NYSE" },
  { symbol: "JCI", name: "Johnson Controls International PLC", exchange: "NYSE" },
  { symbol: "CAR", name: "Avis Budget Group Inc.", exchange: "NASDAQ" },
  { symbol: "HTZ", name: "Hertz Global Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "AAP", name: "Advance Auto Parts Inc.", exchange: "NYSE" },
  { symbol: "AZO", name: "AutoZone Inc.", exchange: "NYSE" },
  { symbol: "ORLY", name: "O'Reilly Automotive Inc.", exchange: "NASDAQ" },
  { symbol: "KMX", name: "CarMax Inc.", exchange: "NYSE" },
  { symbol: "CVNA", name: "Carvana Co.", exchange: "NYSE" },
  { symbol: "TSCO", name: "Tractor Supply Co.", exchange: "NASDAQ" },
  { symbol: "ULTA", name: "Ulta Beauty Inc.", exchange: "NASDAQ" },
  { symbol: "CHWY", name: "Chewy Inc.", exchange: "NYSE" },
  { symbol: "WING", name: "Wingstop Inc.", exchange: "NASDAQ" },
  { symbol: "DPZ", name: "Domino's Pizza Inc.", exchange: "NYSE" },
  { symbol: "YUM", name: "Yum! Brands Inc.", exchange: "NYSE" },
  { symbol: "MCD", name: "McDonald's Corp.", exchange: "NYSE" },
  { symbol: "SBUX", name: "Starbucks Corp.", exchange: "NASDAQ" },
  { symbol: "CMG", name: "Chipotle Mexican Grill Inc.", exchange: "NYSE" },
  { symbol: "QSR", name: "Restaurant Brands International Inc.", exchange: "NYSE" },
  { symbol: "DRI", name: "Darden Restaurants Inc.", exchange: "NYSE" },
  { symbol: "BLMN", name: "Bloomin' Brands Inc.", exchange: "NASDAQ" },
  { symbol: "TXRH", name: "Texas Roadhouse Inc.", exchange: "NASDAQ" },
  { symbol: "CAKE", name: "The Cheesecake Factory Inc.", exchange: "NASDAQ" },
  { symbol: "FWRD", name: "Forward Air Corp.", exchange: "NASDAQ" },
  { symbol: "ODFL", name: "Old Dominion Freight Line Inc.", exchange: "NASDAQ" },
  { symbol: "JBHT", name: "J.B. Hunt Transport Services Inc.", exchange: "NASDAQ" },
  { symbol: "CHRW", name: "C.H. Robinson Worldwide Inc.", exchange: "NASDAQ" },
  { symbol: "EXPD", name: "Expeditors International of Washington Inc.", exchange: "NASDAQ" },
  { symbol: "GXO", name: "GXO Logistics Inc.", exchange: "NYSE" },
  { symbol: "XPO", name: "XPO Inc.", exchange: "NYSE" },
  { symbol: "CSX", name: "CSX Corp.", exchange: "NASDAQ" },
  { symbol: "NSC", name: "Norfolk Southern Corp.", exchange: "NYSE" },
  { symbol: "UNP", name: "Union Pacific Corp.", exchange: "NYSE" },
  { symbol: "KSU", name: "Kansas City Southern", exchange: "NYSE" },
  { symbol: "CP", name: "Canadian Pacific Kansas City Ltd.", exchange: "NYSE" },
  { symbol: "CNI", name: "Canadian National Railway Co.", exchange: "NYSE" },

  // NASDAQ 100 - Additional
  { symbol: "MELI", name: "MercadoLibre Inc.", exchange: "NASDAQ" },
  { symbol: "PDD", name: "PDD Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "BIDU", name: "Baidu Inc.", exchange: "NASDAQ" },
  { symbol: "JD", name: "JD.com Inc.", exchange: "NASDAQ" },
  { symbol: "BABA", name: "Alibaba Group Holding Ltd.", exchange: "NYSE" },
  { symbol: "NIO", name: "NIO Inc.", exchange: "NYSE" },
  { symbol: "LI", name: "Li Auto Inc.", exchange: "NASDAQ" },
  { symbol: "XPEV", name: "XPeng Inc.", exchange: "NYSE" },
  { symbol: "TCOM", name: "Trip.com Group Ltd.", exchange: "NASDAQ" },
  { symbol: "WIX", name: "Wix.com Ltd.", exchange: "NASDAQ" },
  { symbol: "VRSN", name: "VeriSign Inc.", exchange: "NASDAQ" },
  { symbol: "CHKP", name: "Check Point Software Technologies Ltd.", exchange: "NASDAQ" },
  { symbol: "CTSH", name: "Cognizant Technology Solutions Corp.", exchange: "NASDAQ" },
  { symbol: "EPAM", name: "Epam Systems Inc.", exchange: "NYSE" },
  { symbol: "ACN", name: "Accenture PLC", exchange: "NYSE" },
  { symbol: "INFY", name: "Infosys Ltd.", exchange: "NYSE" },
  { symbol: "WIT", name: "Wipro Ltd.", exchange: "NYSE" },
  { symbol: "HDB", name: "HDFC Bank Ltd.", exchange: "NYSE" },
  { symbol: "IBN", name: "ICICI Bank Ltd.", exchange: "NYSE" },
  { symbol: "LYG", name: "Lloyds Banking Group PLC", exchange: "NYSE" },
  { symbol: "BCS", name: "Barclays PLC", exchange: "NYSE" },
  { symbol: "UBS", name: "UBS Group AG", exchange: "NYSE" },
  { symbol: "DB", name: "Deutsche Bank AG", exchange: "NYSE" },
  { symbol: "HSBC", name: "HSBC Holdings PLC", exchange: "NYSE" },
  { symbol: "SAN", name: "Banco Santander S.A.", exchange: "NYSE" },
  { symbol: "BBVA", name: "Banco Bilbao Vizcaya Argentaria S.A.", exchange: "NYSE" },
  { symbol: "TM", name: "Toyota Motor Corp.", exchange: "NYSE" },
  { symbol: "HMC", name: "Honda Motor Co. Ltd.", exchange: "NYSE" },
  { symbol: "SONY", name: "Sony Group Corp.", exchange: "NYSE" },
  { symbol: "SHEL", name: "Shell PLC", exchange: "NYSE" },
  { symbol: "TTE", name: "TotalEnergies SE", exchange: "NYSE" },
  { symbol: "BP", name: "BP PLC", exchange: "NYSE" },
  { symbol: "E", name: "Eni S.p.A.", exchange: "NYSE" },
  { symbol: "PBR", name: "Petroleo Brasileiro S.A.", exchange: "NYSE" },
  { symbol: "EQNR", name: "Equinor ASA", exchange: "NYSE" },
  { symbol: "RIO", name: "Rio Tinto Group", exchange: "NYSE" },
  { symbol: "BHP", name: "BHP Group Ltd.", exchange: "NYSE" },
  { symbol: "SCCO", name: "Southern Copper Corp.", exchange: "NYSE" },
  { symbol: "VALE", name: "Vale S.A.", exchange: "NYSE" },
  { symbol: "GGB", name: "Gerdau S.A.", exchange: "NYSE" },

  // ETFs - Popular
  { symbol: "SPY", name: "SPDR S&P 500 ETF Trust", exchange: "NYSE" },
  { symbol: "QQQ", name: "Invesco QQQ Trust", exchange: "NASDAQ" },
  { symbol: "DIA", name: "SPDR Dow Jones Industrial Average ETF Trust", exchange: "NYSE" },
  { symbol: "IWM", name: "iShares Russell 2000 ETF", exchange: "NYSE" },
  { symbol: "VTI", name: "Vanguard Total Stock Market ETF", exchange: "NYSE" },
  { symbol: "VOO", name: "Vanguard S&P 500 ETF", exchange: "NYSE" },
  { symbol: "IVV", name: "iShares Core S&P 500 ETF", exchange: "NYSE" },
  { symbol: "VEA", name: "Vanguard FTSE Developed Markets ETF", exchange: "NYSE" },
  { symbol: "VWO", name: "Vanguard FTSE Emerging Markets ETF", exchange: "NYSE" },
  { symbol: "BND", name: "Vanguard Total Bond Market ETF", exchange: "NYSE" },
  { symbol: "AGG", name: "iShares Core U.S. Aggregate Bond ETF", exchange: "NYSE" },
  { symbol: "GLD", name: "SPDR Gold Trust", exchange: "NYSE" },
  { symbol: "SLV", name: "iShares Silver Trust", exchange: "NYSE" },
  { symbol: "USO", name: "United States Oil Fund", exchange: "NYSE" },
  { symbol: "TLT", name: "iShares 20+ Year Treasury Bond ETF", exchange: "NASDAQ" },
  { symbol: "IEF", name: "iShares 7-10 Year Treasury Bond ETF", exchange: "NASDAQ" },
  { symbol: "SHY", name: "iShares 1-3 Year Treasury Bond ETF", exchange: "NASDAQ" },
  { symbol: "LQD", name: "iShares iBoxx Investment Grade Corporate Bond ETF", exchange: "NYSE" },
  { symbol: "HYG", name: "iShares iBoxx High Yield Corporate Bond ETF", exchange: "NYSE" },
  { symbol: "XLF", name: "Financial Select Sector SPDR Fund", exchange: "NYSE" },
  { symbol: "XLK", name: "Technology Select Sector SPDR Fund", exchange: "NYSE" },
  { symbol: "XLE", name: "Energy Select Sector SPDR Fund", exchange: "NYSE" },
  { symbol: "XLV", name: "Health Care Select Sector SPDR Fund", exchange: "NYSE" },
  { symbol: "XLI", name: "Industrial Select Sector SPDR Fund", exchange: "NYSE" },
  { symbol: "XLP", name: "Consumer Staples Select Sector SPDR Fund", exchange: "NYSE" },
  { symbol: "XLY", name: "Consumer Discretionary Select Sector SPDR Fund", exchange: "NYSE" },
  { symbol: "XLU", name: "Utilities Select Sector SPDR Fund", exchange: "NYSE" },
  { symbol: "XLRE", name: "Real Estate Select Sector SPDR Fund", exchange: "NYSE" },
  { symbol: "XLC", name: "Communication Services Select Sector SPDR Fund", exchange: "NYSE" },
  { symbol: "VGT", name: "Vanguard Information Technology ETF", exchange: "NYSE" },
  { symbol: "VHT", name: "Vanguard Health Care ETF", exchange: "NYSE" },
  { symbol: "VNQ", name: "Vanguard Real Estate ETF", exchange: "NYSE" },
  { symbol: "VPU", name: "Vanguard Utilities ETF", exchange: "NYSE" },
  { symbol: "VIS", name: "Vanguard Industrials ETF", exchange: "NYSE" },
  { symbol: "VDC", name: "Vanguard Consumer Staples ETF", exchange: "NYSE" },
  { symbol: "VCR", name: "Vanguard Consumer Discretionary ETF", exchange: "NYSE" },
  { symbol: "VAW", name: "Vanguard Materials ETF", exchange: "NYSE" },
  { symbol: "VOX", name: "Vanguard Communication Services ETF", exchange: "NYSE" },
  { symbol: "VDE", name: "Vanguard Energy ETF", exchange: "NYSE" },
  { symbol: "ARCC", name: "Ares Capital Corp.", exchange: "NASDAQ" },
  { symbol: "MAIN", name: "Main Street Capital Corp.", exchange: "NYSE" },
  { symbol: "HTGC", name: "Hercules Capital Inc.", exchange: "NYSE" },
  { symbol: "PSEC", name: "Prospect Capital Corp.", exchange: "NASDAQ" },
  { symbol: "BX", name: "Blackstone Inc.", exchange: "NYSE" },
  { symbol: "KKR", name: "KKR & Co. Inc.", exchange: "NYSE" },
  { symbol: "APO", name: "Apollo Global Management Inc.", exchange: "NYSE" },
  { symbol: "CNS", name: "Cohen & Steers Inc.", exchange: "NYSE" },
  { symbol: "OWL", name: "Blue Owl Capital Inc.", exchange: "NYSE" },
  { symbol: "ARES", name: "Ares Management Corp.", exchange: "NYSE" },
  { symbol: "TPG", name: "TPG Inc.", exchange: "NASDAQ" },
  { symbol: "BAM", name: "Brookfield Asset Management Ltd.", exchange: "NYSE" },

  // More Mid-Cap Stocks
  { symbol: "AA", name: "Alcoa Corp.", exchange: "NYSE" },
  { symbol: "ACVA", name: "ACV Auctions Inc.", exchange: "NASDAQ" },
  { symbol: "ADC", name: "Agree Realty Corp.", exchange: "NYSE" },
  { symbol: "AES", name: "The AES Corp.", exchange: "NYSE" },
  { symbol: "AFG", name: "American Financial Group Inc.", exchange: "NYSE" },
  { symbol: "AGCO", name: "AGCO Corp.", exchange: "NYSE" },
  { symbol: "AGNC", name: "AGNC Investment Corp.", exchange: "NASDAQ" },
  { symbol: "AIG", name: "American International Group Inc.", exchange: "NYSE" },
  { symbol: "AIZ", name: "Assurant Inc.", exchange: "NYSE" },
  { symbol: "AKAM", name: "Akamai Technologies Inc.", exchange: "NASDAQ" },
  { symbol: "ALB", name: "Albemarle Corp.", exchange: "NYSE" },
  { symbol: "ALGN", name: "Align Technology Inc.", exchange: "NASDAQ" },
  { symbol: "ALL", name: "The Allstate Corp.", exchange: "NYSE" },
  { symbol: "ALLE", name: "Allegion PLC", exchange: "NYSE" },
  { symbol: "ALLY", name: "Ally Financial Inc.", exchange: "NYSE" },
  { symbol: "ALNY", name: "Alnylam Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "AMAT", name: "Applied Materials Inc.", exchange: "NASDAQ" },
  { symbol: "AMCR", name: "Amcor PLC", exchange: "NYSE" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", exchange: "NASDAQ" },
  { symbol: "AME", name: "AMETEK Inc.", exchange: "NYSE" },
  { symbol: "AMGN", name: "Amgen Inc.", exchange: "NASDAQ" },
  { symbol: "AMP", name: "Ameriprise Financial Inc.", exchange: "NYSE" },
  { symbol: "AMT", name: "American Tower Corp.", exchange: "NYSE" },
  { symbol: "ARE", name: "Alexandria Real Estate Equities Inc.", exchange: "NYSE" },
  { symbol: "ATO", name: "Atmos Energy Corp.", exchange: "NYSE" },
  { symbol: "AVB", name: "AvalonBay Communities Inc.", exchange: "NYSE" },
  { symbol: "AVGO", name: "Broadcom Inc.", exchange: "NASDAQ" },
  { symbol: "AVTR", name: "Avantor Inc.", exchange: "NYSE" },
  { symbol: "AWK", name: "American Water Works Co. Inc.", exchange: "NYSE" },
  { symbol: "AZO", name: "AutoZone Inc.", exchange: "NYSE" },
  { symbol: "BAX", name: "Baxter International Inc.", exchange: "NYSE" },
  { symbol: "BBY", name: "Best Buy Co. Inc.", exchange: "NYSE" },
  { symbol: "BEN", name: "Franklin Resources Inc.", exchange: "NYSE" },
  { symbol: "BIO", name: "Bio-Rad Laboratories Inc.", exchange: "NYSE" },
  { symbol: "BK", name: "The Bank of New York Mellon Corp.", exchange: "NYSE" },
  { symbol: "BKR", name: "Baker Hughes Co.", exchange: "NASDAQ" },
  { symbol: "BLK", name: "BlackRock Inc.", exchange: "NYSE" },
  { symbol: "BMRN", name: "BioMarin Pharmaceutical Inc.", exchange: "NASDAQ" },
  { symbol: "BSX", name: "Boston Scientific Corp.", exchange: "NYSE" },
  { symbol: "BWA", name: "BorgWarner Inc.", exchange: "NYSE" },
  { symbol: "BXP", name: "Boston Properties Inc.", exchange: "NYSE" },
  { symbol: "CACC", name: "Credit Acceptance Corp.", exchange: "NASDAQ" },
  { symbol: "CAG", name: "Conagra Brands Inc.", exchange: "NYSE" },
  { symbol: "CAH", name: "Cardinal Health Inc.", exchange: "NYSE" },
  { symbol: "CARR", name: "Carrier Global Corp.", exchange: "NYSE" },
  { symbol: "CAT", name: "Caterpillar Inc.", exchange: "NYSE" },
  { symbol: "CBRE", name: "CBRE Group Inc.", exchange: "NYSE" },
  { symbol: "CCK", name: "Crown Holdings Inc.", exchange: "NYSE" },
  { symbol: "CDNS", name: "Cadence Design Systems Inc.", exchange: "NASDAQ" },
  { symbol: "CE", name: "Celanese Corp.", exchange: "NYSE" },
  { symbol: "CBOE", name: "Cboe Global Markets Inc.", exchange: "NYSE" },
  { symbol: "CFG", name: "Citizens Financial Group Inc.", exchange: "NYSE" },
  { symbol: "CHD", name: "Church & Dwight Co. Inc.", exchange: "NYSE" },
  { symbol: "CHRW", name: "C.H. Robinson Worldwide Inc.", exchange: "NASDAQ" },
  { symbol: "CHTR", name: "Charter Communications Inc.", exchange: "NASDAQ" },
  { symbol: "CINF", name: "Cincinnati Financial Corp.", exchange: "NASDAQ" },
  { symbol: "CLX", name: "The Clorox Co.", exchange: "NYSE" },
  { symbol: "CMA", name: "Comerica Inc.", exchange: "NYSE" },
  { symbol: "CMI", name: "Cummins Inc.", exchange: "NYSE" },
  { symbol: "CMS", name: "CMS Energy Corp.", exchange: "NYSE" },
  { symbol: "CNC", name: "Centene Corp.", exchange: "NYSE" },
  { symbol: "CNP", name: "CenterPoint Energy Inc.", exchange: "NYSE" },
  { symbol: "COF", name: "Capital One Financial Corp.", exchange: "NYSE" },
  { symbol: "COO", name: "The Cooper Companies Inc.", exchange: "NYSE" },
  { symbol: "CPAY", name: "Corpay Inc.", exchange: "NYSE" },
  { symbol: "CPRT", name: "Copart Inc.", exchange: "NASDAQ" },
  { symbol: "CRL", name: "Charles River Laboratories International Inc.", exchange: "NYSE" },
  { symbol: "CROX", name: "Crocs Inc.", exchange: "NASDAQ" },
  { symbol: "CSGP", name: "CoStar Group Inc.", exchange: "NASDAQ" },
  { symbol: "CSL", name: "Carlisle Companies Inc.", exchange: "NYSE" },
  { symbol: "CTAS", name: "Cintas Corp.", exchange: "NASDAQ" },
  { symbol: "CTLT", name: "Catalent Inc.", exchange: "NYSE" },
  { symbol: "CTRA", name: "Coterra Energy Inc.", exchange: "NYSE" },
  { symbol: "CTVA", name: "Corteva Inc.", exchange: "NYSE" },
  { symbol: "CUK", name: "Carnival PLC", exchange: "NYSE" },
  { symbol: "CVS", name: "CVS Health Corp.", exchange: "NYSE" },
  { symbol: "DAL", name: "Delta Air Lines Inc.", exchange: "NYSE" },
  { symbol: "DAY", name: "Dayforce Inc.", exchange: "NYSE" },
  { symbol: "DD", name: "DuPont de Nemours Inc.", exchange: "NYSE" },
  { symbol: "DE", name: "Deere & Co.", exchange: "NYSE" },
  { symbol: "DECK", name: "Deckers Outdoor Corp.", exchange: "NYSE" },
  { symbol: "DFS", name: "Discover Financial Services", exchange: "NYSE" },
  { symbol: "DG", name: "Dollar General Corp.", exchange: "NYSE" },
  { symbol: "DGX", name: "Quest Diagnostics Inc.", exchange: "NYSE" },
  { symbol: "DHI", name: "D.R. Horton Inc.", exchange: "NYSE" },
  { symbol: "DHR", name: "Danaher Corp.", exchange: "NYSE" },
  { symbol: "DINO", name: "HF Sinclair Corp.", exchange: "NYSE" },
  { symbol: "DIS", name: "The Walt Disney Co.", exchange: "NYSE" },
  { symbol: "DKNG", name: "DraftKings Inc.", exchange: "NASDAQ" },
  { symbol: "DKS", name: "Dick's Sporting Goods Inc.", exchange: "NYSE" },
  { symbol: "DLR", name: "Digital Realty Trust Inc.", exchange: "NYSE" },
  { symbol: "DLTR", name: "Dollar Tree Inc.", exchange: "NASDAQ" },
  { symbol: "DOCU", name: "DocuSign Inc.", exchange: "NASDAQ" },
  { symbol: "DOV", name: "Dover Corp.", exchange: "NYSE" },
  { symbol: "DOW", name: "Dow Inc.", exchange: "NYSE" },
  { symbol: "DPZ", name: "Domino's Pizza Inc.", exchange: "NYSE" },
  { symbol: "DRI", name: "Darden Restaurants Inc.", exchange: "NYSE" },
  { symbol: "DTE", name: "DTE Energy Co.", exchange: "NYSE" },
  { symbol: "DUK", name: "Duke Energy Corp.", exchange: "NYSE" },
  { symbol: "DVA", name: "DaVita Inc.", exchange: "NYSE" },
  { symbol: "DVN", name: "Devon Energy Corp.", exchange: "NYSE" },
  { symbol: "DXCM", name: "Dexcom Inc.", exchange: "NASDAQ" },
  { symbol: "EA", name: "Electronic Arts Inc.", exchange: "NASDAQ" },
  { symbol: "EBAY", name: "eBay Inc.", exchange: "NASDAQ" },
  { symbol: "ECL", name: "Ecolab Inc.", exchange: "NYSE" },
  { symbol: "ED", name: "Consolidated Edison Inc.", exchange: "NYSE" },
  { symbol: "EFX", name: "Equifax Inc.", exchange: "NYSE" },
  { symbol: "EIX", name: "Edison International", exchange: "NYSE" },
  { symbol: "EL", name: "The Estee Lauder Companies Inc.", exchange: "NYSE" },
  { symbol: "EMN", name: "Eastman Chemical Co.", exchange: "NYSE" },
  { symbol: "EMR", name: "Emerson Electric Co.", exchange: "NYSE" },
  { symbol: "ENPH", name: "Enphase Energy Inc.", exchange: "NASDAQ" },
  { symbol: "EOG", name: "EOG Resources Inc.", exchange: "NYSE" },
  { symbol: "EPAM", name: "Epam Systems Inc.", exchange: "NYSE" },
  { symbol: "EQIX", name: "Equinix Inc.", exchange: "NYSE" },
  { symbol: "EQR", name: "Equity Residential", exchange: "NYSE" },
  { symbol: "ES", name: "Eversource Energy", exchange: "NYSE" },
  { symbol: "ESS", name: "Essex Property Trust Inc.", exchange: "NYSE" },
  { symbol: "ETN", name: "Eaton Corp. PLC", exchange: "NYSE" },
  { symbol: "ETR", name: "Entergy Corp.", exchange: "NYSE" },
  { symbol: "EVRG", name: "Evergy Inc.", exchange: "NYSE" },
  { symbol: "EW", name: "Edwards Lifesciences Corp.", exchange: "NYSE" },
  { symbol: "EXC", name: "Exelon Corp.", exchange: "NASDAQ" },
  { symbol: "EXPD", name: "Expeditors International of Washington Inc.", exchange: "NASDAQ" },
  { symbol: "EXPE", name: "Expedia Group Inc.", exchange: "NASDAQ" },
  { symbol: "EXR", name: "Extra Space Storage Inc.", exchange: "NYSE" },
  { symbol: "F", name: "Ford Motor Co.", exchange: "NYSE" },
  { symbol: "FANG", name: "Diamondback Energy Inc.", exchange: "NASDAQ" },
  { symbol: "FAST", name: "Fastenal Co.", exchange: "NASDAQ" },
  { symbol: "FCX", name: "Freeport-McMoRan Inc.", exchange: "NYSE" },
  { symbol: "FDS", name: "FactSet Research Systems Inc.", exchange: "NYSE" },
  { symbol: "FDX", name: "FedEx Corp.", exchange: "NYSE" },
  { symbol: "FE", name: "FirstEnergy Corp.", exchange: "NYSE" },
  { symbol: "FFIV", name: "F5 Inc.", exchange: "NASDAQ" },
  { symbol: "FI", name: "Fiserv Inc.", exchange: "NYSE" },
  { symbol: "FICO", name: "Fair Isaac Corp.", exchange: "NYSE" },
  { symbol: "FIS", name: "Fidelity National Information Services Inc.", exchange: "NYSE" },
  { symbol: "FITB", name: "Fifth Third Bancorp", exchange: "NASDAQ" },
  { symbol: "FMC", name: "FMC Corp.", exchange: "NYSE" },
  { symbol: "FOX", name: "Fox Corp.", exchange: "NASDAQ" },
  { symbol: "FRT", name: "Federal Realty Investment Trust", exchange: "NYSE" },
  { symbol: "FSLR", name: "First Solar Inc.", exchange: "NASDAQ" },
  { symbol: "FTNT", name: "Fortinet Inc.", exchange: "NASDAQ" },
  { symbol: "FTV", name: "Fortive Corp.", exchange: "NYSE" },
  { symbol: "GD", name: "General Dynamics Corp.", exchange: "NYSE" },
  { symbol: "GE", name: "General Electric Co.", exchange: "NYSE" },
  { symbol: "GEN", name: "Gen Digital Inc.", exchange: "NASDAQ" },
  { symbol: "GILD", name: "Gilead Sciences Inc.", exchange: "NASDAQ" },
  { symbol: "GIS", name: "General Mills Inc.", exchange: "NYSE" },
  { symbol: "GL", name: "Globe Life Inc.", exchange: "NYSE" },
  { symbol: "GLW", name: "Corning Inc.", exchange: "NYSE" },
  { symbol: "GM", name: "General Motors Co.", exchange: "NYSE" },
  { symbol: "GNRC", name: "Generac Holdings Inc.", exchange: "NYSE" },
  { symbol: "GPC", name: "Genuine Parts Co.", exchange: "NYSE" },
  { symbol: "GPN", name: "Global Payments Inc.", exchange: "NYSE" },
  { symbol: "GRMN", name: "Garmin Ltd.", exchange: "NYSE" },
  { symbol: "GS", name: "The Goldman Sachs Group Inc.", exchange: "NYSE" },
  { symbol: "GWW", name: "W.W. Grainger Inc.", exchange: "NYSE" },
  { symbol: "HAL", name: "Halliburton Co.", exchange: "NYSE" },
  { symbol: "HAS", name: "Hasbro Inc.", exchange: "NASDAQ" },
  { symbol: "HBAN", name: "Huntington Bancshares Inc.", exchange: "NASDAQ" },
  { symbol: "HCA", name: "HCA Healthcare Inc.", exchange: "NYSE" },
  { symbol: "HD", name: "The Home Depot Inc.", exchange: "NYSE" },
  { symbol: "HES", name: "Hess Corp.", exchange: "NYSE" },
  { symbol: "HIG", name: "The Hartford Financial Services Group Inc.", exchange: "NYSE" },
  { symbol: "HLT", name: "Hilton Worldwide Holdings Inc.", exchange: "NYSE" },
  { symbol: "HOLX", name: "Hologic Inc.", exchange: "NASDAQ" },
  { symbol: "HON", name: "Honeywell International Inc.", exchange: "NASDAQ" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise Co.", exchange: "NYSE" },
  { symbol: "HPQ", name: "HP Inc.", exchange: "NYSE" },
  { symbol: "HRL", name: "Hormel Foods Corp.", exchange: "NYSE" },
  { symbol: "HSIC", name: "Henry Schein Inc.", exchange: "NASDAQ" },
  { symbol: "HST", name: "Host Hotels & Resorts Inc.", exchange: "NASDAQ" },
  { symbol: "HSY", name: "The Hershey Co.", exchange: "NYSE" },
  { symbol: "HUBB", name: "Hubbell Inc.", exchange: "NYSE" },
  { symbol: "HUM", name: "Humana Inc.", exchange: "NYSE" },
  { symbol: "HWM", name: "Howmet Aerospace Inc.", exchange: "NYSE" },
  { symbol: "IBM", name: "International Business Machines Corp.", exchange: "NYSE" },
  { symbol: "ICE", name: "Intercontinental Exchange Inc.", exchange: "NYSE" },
  { symbol: "IDXX", name: "IDEXX Laboratories Inc.", exchange: "NASDAQ" },
  { symbol: "IEX", name: "IDEX Corp.", exchange: "NYSE" },
  { symbol: "IFF", name: "International Flavors & Fragrances Inc.", exchange: "NYSE" },
  { symbol: "INCY", name: "Incyte Corp.", exchange: "NASDAQ" },
  { symbol: "INTC", name: "Intel Corp.", exchange: "NASDAQ" },
  { symbol: "INTU", name: "Intuit Inc.", exchange: "NASDAQ" },
  { symbol: "INVH", name: "Invitation Homes Inc.", exchange: "NYSE" },
  { symbol: "IP", name: "International Paper Co.", exchange: "NYSE" },
  { symbol: "IPG", name: "The Interpublic Group of Companies Inc.", exchange: "NYSE" },
  { symbol: "IQV", name: "IQVIA Holdings Inc.", exchange: "NYSE" },
  { symbol: "IR", name: "Ingersoll Rand Inc.", exchange: "NYSE" },
  { symbol: "IRM", name: "Iron Mountain Inc.", exchange: "NYSE" },
  { symbol: "ISRG", name: "Intuitive Surgical Inc.", exchange: "NASDAQ" },
  { symbol: "IT", name: "Gartner Inc.", exchange: "NYSE" },
  { symbol: "ITW", name: "Illinois Tool Works Inc.", exchange: "NYSE" },
  { symbol: "IVZ", name: "Invesco Ltd.", exchange: "NYSE" },
  { symbol: "J", name: "Jacobs Solutions Inc.", exchange: "NYSE" },
  { symbol: "JBHT", name: "J.B. Hunt Transport Services Inc.", exchange: "NASDAQ" },
  { symbol: "JCI", name: "Johnson Controls International PLC", exchange: "NYSE" },
  { symbol: "JEF", name: "Jefferies Financial Group Inc.", exchange: "NYSE" },
  { symbol: "JKHY", name: "Jack Henry & Associates Inc.", exchange: "NASDAQ" },
  { symbol: "JNJ", name: "Johnson & Johnson", exchange: "NYSE" },
  { symbol: "JNPR", name: "Juniper Networks Inc.", exchange: "NYSE" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", exchange: "NYSE" },
  { symbol: "K", name: "Kellanova", exchange: "NYSE" },
  { symbol: "KDP", name: "Keurig Dr Pepper Inc.", exchange: "NASDAQ" },
  { symbol: "KEY", name: "KeyCorp", exchange: "NYSE" },
  { symbol: "KEYS", name: "Keysight Technologies Inc.", exchange: "NYSE" },
  { symbol: "KHC", name: "The Kraft Heinz Co.", exchange: "NASDAQ" },
  { symbol: "KIM", name: "Kimco Realty Corp.", exchange: "NYSE" },
  { symbol: "KKR", name: "KKR & Co. Inc.", exchange: "NYSE" },
  { symbol: "KLAC", name: "KLA Corp.", exchange: "NASDAQ" },
  { symbol: "KMB", name: "Kimberly-Clark Corp.", exchange: "NYSE" },
  { symbol: "KMI", name: "Kinder Morgan Inc.", exchange: "NYSE" },
  { symbol: "KMX", name: "CarMax Inc.", exchange: "NYSE" },
  { symbol: "KO", name: "The Coca-Cola Co.", exchange: "NYSE" },
  { symbol: "KR", name: "The Kroger Co.", exchange: "NYSE" },
  { symbol: "L", name: "Loews Corp.", exchange: "NYSE" },
  { symbol: "LDOS", name: "Leidos Holdings Inc.", exchange: "NYSE" },
  { symbol: "LEN", name: "Lennar Corp.", exchange: "NYSE" },
  { symbol: "LH", name: "Labcorp Holdings Inc.", exchange: "NYSE" },
  { symbol: "LHX", name: "L3Harris Technologies Inc.", exchange: "NYSE" },
  { symbol: "LIN", name: "Linde PLC", exchange: "NASDAQ" },
  { symbol: "LKQ", name: "LKQ Corp.", exchange: "NASDAQ" },
  { symbol: "LLY", name: "Eli Lilly and Co.", exchange: "NYSE" },
  { symbol: "LMT", name: "Lockheed Martin Corp.", exchange: "NYSE" },
  { symbol: "LNT", name: "Alliant Energy Corp.", exchange: "NASDAQ" },
  { symbol: "LOW", name: "Lowe's Companies Inc.", exchange: "NYSE" },
  { symbol: "LRCX", name: "Lam Research Corp.", exchange: "NASDAQ" },
  { symbol: "LULU", name: "lululemon athletica Inc.", exchange: "NASDAQ" },
  { symbol: "LVS", name: "Las Vegas Sands Corp.", exchange: "NYSE" },
  { symbol: "LYB", name: "LyondellBasell Industries N.V.", exchange: "NYSE" },
  { symbol: "LYV", name: "Live Nation Entertainment Inc.", exchange: "NYSE" },
  { symbol: "MA", name: "Mastercard Inc.", exchange: "NYSE" },
  { symbol: "MAA", name: "Mid-America Apartment Communities Inc.", exchange: "NYSE" },
  { symbol: "MAR", name: "Marriott International Inc.", exchange: "NASDAQ" },
  { symbol: "MAS", name: "Masco Corp.", exchange: "NYSE" },
  { symbol: "MCD", name: "McDonald's Corp.", exchange: "NYSE" },
  { symbol: "MCHP", name: "Microchip Technology Inc.", exchange: "NASDAQ" },
  { symbol: "MCK", name: "McKesson Corp.", exchange: "NYSE" },
  { symbol: "MCO", name: "Moody's Corp.", exchange: "NYSE" },
  { symbol: "MDLZ", name: "Mondelez International Inc.", exchange: "NASDAQ" },
  { symbol: "MDT", name: "Medtronic PLC", exchange: "NYSE" },
  { symbol: "MET", name: "MetLife Inc.", exchange: "NYSE" },
  { symbol: "META", name: "Meta Platforms Inc.", exchange: "NASDAQ" },
  { symbol: "MGM", name: "MGM Resorts International", exchange: "NYSE" },
  { symbol: "MKC", name: "McCormick & Co. Inc.", exchange: "NYSE" },
  { symbol: "MKL", name: "Markel Group Inc.", exchange: "NYSE" },
  { symbol: "MLM", name: "Martin Marietta Materials Inc.", exchange: "NYSE" },
  { symbol: "MMC", name: "Marsh & McLennan Companies Inc.", exchange: "NYSE" },
  { symbol: "MMM", name: "3M Co.", exchange: "NYSE" },
  { symbol: "MNST", name: "Monster Beverage Corp.", exchange: "NASDAQ" },
  { symbol: "MO", name: "Altria Group Inc.", exchange: "NYSE" },
  { symbol: "MOH", name: "Molina Healthcare Inc.", exchange: "NYSE" },
  { symbol: "MOS", name: "The Mosaic Co.", exchange: "NYSE" },
  { symbol: "MPC", name: "Marathon Petroleum Corp.", exchange: "NYSE" },
  { symbol: "MPWR", name: "Monolithic Power Systems Inc.", exchange: "NASDAQ" },
  { symbol: "MRK", name: "Merck & Co. Inc.", exchange: "NYSE" },
  { symbol: "MRNA", name: "Moderna Inc.", exchange: "NASDAQ" },
  { symbol: "MS", name: "Morgan Stanley", exchange: "NYSE" },
  { symbol: "MSCI", name: "MSCI Inc.", exchange: "NYSE" },
  { symbol: "MSFT", name: "Microsoft Corp.", exchange: "NASDAQ" },
  { symbol: "MSI", name: "Motorola Solutions Inc.", exchange: "NYSE" },
  { symbol: "MTB", name: "M&T Bank Corp.", exchange: "NYSE" },
  { symbol: "MTCH", name: "Match Group Inc.", exchange: "NASDAQ" },
  { symbol: "MTD", name: "Mettler-Toledo International Inc.", exchange: "NYSE" },
  { symbol: "MU", name: "Micron Technology Inc.", exchange: "NASDAQ" },
  { symbol: "NDAQ", name: "Nasdaq Inc.", exchange: "NASDAQ" },
  { symbol: "NDSN", name: "Nordson Corp.", exchange: "NASDAQ" },
  { symbol: "NEE", name: "NextEra Energy Inc.", exchange: "NYSE" },
  { symbol: "NEM", name: "Newmont Corp.", exchange: "NYSE" },
  { symbol: "NFLX", name: "Netflix Inc.", exchange: "NASDAQ" },
  { symbol: "NI", name: "NiSource Inc.", exchange: "NYSE" },
  { symbol: "NKE", name: "Nike Inc.", exchange: "NYSE" },
  { symbol: "NOC", name: "Northrop Grumman Corp.", exchange: "NYSE" },
  { symbol: "NOW", name: "ServiceNow Inc.", exchange: "NYSE" },
  { symbol: "NRG", name: "NRG Energy Inc.", exchange: "NYSE" },
  { symbol: "NSC", name: "Norfolk Southern Corp.", exchange: "NYSE" },
  { symbol: "NTAP", name: "NetApp Inc.", exchange: "NASDAQ" },
  { symbol: "NTRS", name: "Northern Trust Corp.", exchange: "NASDAQ" },
  { symbol: "NUE", name: "Nucor Corp.", exchange: "NYSE" },
  { symbol: "NVDA", name: "NVIDIA Corp.", exchange: "NASDAQ" },
  { symbol: "NVR", name: "NVR Inc.", exchange: "NYSE" },
  { symbol: "NWSA", name: "News Corp.", exchange: "NASDAQ" },
  { symbol: "NXPI", name: "NXP Semiconductors N.V.", exchange: "NASDAQ" },
  { symbol: "ODFL", name: "Old Dominion Freight Line Inc.", exchange: "NASDAQ" },
  { symbol: "OKE", name: "ONEOK Inc.", exchange: "NYSE" },
  { symbol: "OMC", name: "Omnicom Group Inc.", exchange: "NYSE" },
  { symbol: "ON", name: "ON Semiconductor Corp.", exchange: "NASDAQ" },
  { symbol: "ORCL", name: "Oracle Corp.", exchange: "NYSE" },
  { symbol: "ORLY", name: "O'Reilly Automotive Inc.", exchange: "NASDAQ" },
  { symbol: "OTIS", name: "Otis Worldwide Corp.", exchange: "NYSE" },
  { symbol: "OXY", name: "Occidental Petroleum Corp.", exchange: "NYSE" },
  { symbol: "PANW", name: "Palo Alto Networks Inc.", exchange: "NASDAQ" },
  { symbol: "PARA", name: "Paramount Global", exchange: "NASDAQ" },
  { symbol: "PAYC", name: "Paycom Software Inc.", exchange: "NYSE" },
  { symbol: "PAYX", name: "Paychex Inc.", exchange: "NASDAQ" },
  { symbol: "PCAR", name: "PACCAR Inc.", exchange: "NASDAQ" },
  { symbol: "PCG", name: "PG&E Corp.", exchange: "NYSE" },
  { symbol: "PEG", name: "Public Service Enterprise Group Inc.", exchange: "NYSE" },
  { symbol: "PEP", name: "PepsiCo Inc.", exchange: "NASDAQ" },
  { symbol: "PFE", name: "Pfizer Inc.", exchange: "NYSE" },
  { symbol: "PFG", name: "Principal Financial Group Inc.", exchange: "NASDAQ" },
  { symbol: "PG", name: "The Procter & Gamble Co.", exchange: "NYSE" },
  { symbol: "PGR", name: "The Progressive Corp.", exchange: "NYSE" },
  { symbol: "PH", name: "Parker-Hannifin Corp.", exchange: "NYSE" },
  { symbol: "PHM", name: "PulteGroup Inc.", exchange: "NYSE" },
  { symbol: "PKG", name: "Packaging Corp. of America", exchange: "NYSE" },
  { symbol: "PLD", name: "Prologis Inc.", exchange: "NYSE" },
  { symbol: "PLTR", name: "Palantir Technologies Inc.", exchange: "NASDAQ" },
  { symbol: "PM", name: "Philip Morris International Inc.", exchange: "NYSE" },
  { symbol: "PNC", name: "The PNC Financial Services Group Inc.", exchange: "NYSE" },
  { symbol: "PNR", name: "Pentair PLC", exchange: "NYSE" },
  { symbol: "POOL", name: "Pool Corp.", exchange: "NASDAQ" },
  { symbol: "PPG", name: "PPG Industries Inc.", exchange: "NYSE" },
  { symbol: "PPL", name: "PPL Corp.", exchange: "NYSE" },
  { symbol: "PRU", name: "Prudential Financial Inc.", exchange: "NYSE" },
  { symbol: "PSA", name: "Public Storage", exchange: "NYSE" },
  { symbol: "PSX", name: "Phillips 66", exchange: "NYSE" },
  { symbol: "PWR", name: "Quanta Services Inc.", exchange: "NYSE" },
  { symbol: "PXD", name: "Pioneer Natural Resources Co.", exchange: "NYSE" },
  { symbol: "PYPL", name: "PayPal Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "QCOM", name: "Qualcomm Inc.", exchange: "NASDAQ" },
  { symbol: "QRVO", name: "Qorvo Inc.", exchange: "NASDAQ" },
  { symbol: "RCL", name: "Royal Caribbean Cruises Ltd.", exchange: "NYSE" },
  { symbol: "REG", name: "Regency Centers Corp.", exchange: "NASDAQ" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "RF", name: "Regions Financial Corp.", exchange: "NYSE" },
  { symbol: "RJF", name: "Raymond James Financial Inc.", exchange: "NYSE" },
  { symbol: "RL", name: "Ralph Lauren Corp.", exchange: "NYSE" },
  { symbol: "RMD", name: "ResMed Inc.", exchange: "NYSE" },
  { symbol: "ROK", name: "Rockwell Automation Inc.", exchange: "NYSE" },
  { symbol: "ROL", name: "Rollins Inc.", exchange: "NYSE" },
  { symbol: "ROP", name: "Roper Technologies Inc.", exchange: "NYSE" },
  { symbol: "ROST", name: "Ross Stores Inc.", exchange: "NASDAQ" },
  { symbol: "RPM", name: "RPM International Inc.", exchange: "NYSE" },
  { symbol: "RSG", name: "Republic Services Inc.", exchange: "NYSE" },
  { symbol: "RTX", name: "RTX Corp.", exchange: "NYSE" },
  { symbol: "SBAC", name: "SBA Communications Corp.", exchange: "NASDAQ" },
  { symbol: "SBUX", name: "Starbucks Corp.", exchange: "NASDAQ" },
  { symbol: "SCHW", name: "The Charles Schwab Corp.", exchange: "NYSE" },
  { symbol: "SHW", name: "The Sherwin-Williams Co.", exchange: "NYSE" },
  { symbol: "SJM", name: "The J.M. Smucker Co.", exchange: "NYSE" },
  { symbol: "SLB", name: "Schlumberger N.V.", exchange: "NYSE" },
  { symbol: "SMCI", name: "Super Micro Computer Inc.", exchange: "NASDAQ" },
  { symbol: "SNA", name: "Snap-on Inc.", exchange: "NYSE" },
  { symbol: "SNAP", name: "Snap Inc.", exchange: "NYSE" },
  { symbol: "SNPS", name: "Synopsys Inc.", exchange: "NASDAQ" },
  { symbol: "SO", name: "The Southern Co.", exchange: "NYSE" },
  { symbol: "SOLV", name: "Solventum Corp.", exchange: "NYSE" },
  { symbol: "SPG", name: "Simon Property Group Inc.", exchange: "NYSE" },
  { symbol: "SPGI", name: "S&P Global Inc.", exchange: "NYSE" },
  { symbol: "SQ", name: "Block Inc.", exchange: "NYSE" },
  { symbol: "SRE", name: "Sempra", exchange: "NYSE" },
  { symbol: "STE", name: "STERIS PLC", exchange: "NYSE" },
  { symbol: "STLD", name: "Steel Dynamics Inc.", exchange: "NASDAQ" },
  { symbol: "STT", name: "State Street Corp.", exchange: "NYSE" },
  { symbol: "STX", name: "Seagate Technology Holdings PLC", exchange: "NASDAQ" },
  { symbol: "STZ", name: "Constellation Brands Inc.", exchange: "NYSE" },
  { symbol: "SWKS", name: "Skyworks Solutions Inc.", exchange: "NASDAQ" },
  { symbol: "SYF", name: "Synchrony Financial", exchange: "NYSE" },
  { symbol: "SYK", name: "Stryker Corp.", exchange: "NYSE" },
  { symbol: "T", name: "AT&T Inc.", exchange: "NYSE" },
  { symbol: "TAP", name: "Molson Coors Beverage Co.", exchange: "NYSE" },
  { symbol: "TDG", name: "TransDigm Group Inc.", exchange: "NYSE" },
  { symbol: "TDY", name: "Teledyne Technologies Inc.", exchange: "NYSE" },
  { symbol: "TECH", name: "Bio-Techne Corp.", exchange: "NASDAQ" },
  { symbol: "TEL", name: "TE Connectivity Ltd.", exchange: "NYSE" },
  { symbol: "TER", name: "Teradyne Inc.", exchange: "NASDAQ" },
  { symbol: "TFC", name: "Truist Financial Corp.", exchange: "NYSE" },
  { symbol: "TFX", name: "Teleflex Inc.", exchange: "NYSE" },
  { symbol: "TGT", name: "Target Corp.", exchange: "NYSE" },
  { symbol: "TJX", name: "The TJX Companies Inc.", exchange: "NYSE" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc.", exchange: "NYSE" },
  { symbol: "TMUS", name: "T-Mobile US Inc.", exchange: "NASDAQ" },
  { symbol: "TPR", name: "Tapestry Inc.", exchange: "NYSE" },
  { symbol: "TRGP", name: "Targa Resources Corp.", exchange: "NYSE" },
  { symbol: "TROW", name: "T. Rowe Price Group Inc.", exchange: "NASDAQ" },
  { symbol: "TRV", name: "The Travelers Companies Inc.", exchange: "NYSE" },
  { symbol: "TSCO", name: "Tractor Supply Co.", exchange: "NASDAQ" },
  { symbol: "TSLA", name: "Tesla Inc.", exchange: "NASDAQ" },
  { symbol: "TSN", name: "Tyson Foods Inc.", exchange: "NYSE" },
  { symbol: "TT", name: "Trane Technologies PLC", exchange: "NYSE" },
  { symbol: "TTWO", name: "Take-Two Interactive Software Inc.", exchange: "NASDAQ" },
  { symbol: "TXN", name: "Texas Instruments Inc.", exchange: "NASDAQ" },
  { symbol: "TXT", name: "Textron Inc.", exchange: "NYSE" },
  { symbol: "TYL", name: "Tyler Technologies Inc.", exchange: "NYSE" },
  { symbol: "UAL", name: "United Airlines Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "UBER", name: "Uber Technologies Inc.", exchange: "NYSE" },
  { symbol: "UDR", name: "UDR Inc.", exchange: "NYSE" },
  { symbol: "UHS", name: "Universal Health Services Inc.", exchange: "NYSE" },
  { symbol: "ULTA", name: "Ulta Beauty Inc.", exchange: "NASDAQ" },
  { symbol: "UNH", name: "UnitedHealth Group Inc.", exchange: "NYSE" },
  { symbol: "UNP", name: "Union Pacific Corp.", exchange: "NYSE" },
  { symbol: "UPS", name: "United Parcel Service Inc.", exchange: "NYSE" },
  { symbol: "URI", name: "United Rentals Inc.", exchange: "NYSE" },
  { symbol: "USB", name: "U.S. Bancorp", exchange: "NYSE" },
  { symbol: "V", name: "Visa Inc.", exchange: "NYSE" },
  { symbol: "VFC", name: "V.F. Corp.", exchange: "NYSE" },
  { symbol: "VICI", name: "VICI Properties Inc.", exchange: "NYSE" },
  { symbol: "VLO", name: "Valero Energy Corp.", exchange: "NYSE" },
  { symbol: "VLTO", name: "Veralto Corp.", exchange: "NYSE" },
  { symbol: "VMC", name: "Vulcan Materials Co.", exchange: "NYSE" },
  { symbol: "VRSK", name: "Verisk Analytics Inc.", exchange: "NASDAQ" },
  { symbol: "VRSN", name: "VeriSign Inc.", exchange: "NASDAQ" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "VST", name: "Vistra Corp.", exchange: "NYSE" },
  { symbol: "VTR", name: "Ventas Inc.", exchange: "NYSE" },
  { symbol: "VTRS", name: "Viatris Inc.", exchange: "NASDAQ" },
  { symbol: "VZ", name: "Verizon Communications Inc.", exchange: "NYSE" },
  { symbol: "WAB", name: "Westinghouse Air Brake Technologies Corp.", exchange: "NYSE" },
  { symbol: "WAT", name: "Waters Corp.", exchange: "NYSE" },
  { symbol: "WBA", name: "Walgreens Boots Alliance Inc.", exchange: "NASDAQ" },
  { symbol: "WBD", name: "Warner Bros. Discovery Inc.", exchange: "NASDAQ" },
  { symbol: "WDC", name: "Western Digital Corp.", exchange: "NASDAQ" },
  { symbol: "WDAY", name: "Workday Inc.", exchange: "NASDAQ" },
  { symbol: "WEC", name: "WEC Energy Group Inc.", exchange: "NYSE" },
  { symbol: "WELL", name: "Welltower Inc.", exchange: "NYSE" },
  { symbol: "WFC", name: "Wells Fargo & Co.", exchange: "NYSE" },
  { symbol: "WHR", name: "Whirlpool Corp.", exchange: "NYSE" },
  { symbol: "WM", name: "Waste Management Inc.", exchange: "NYSE" },
  { symbol: "WMB", name: "The Williams Companies Inc.", exchange: "NYSE" },
  { symbol: "WMT", name: "Walmart Inc.", exchange: "NYSE" },
  { symbol: "WRB", name: "W.R. Berkley Corp.", exchange: "NYSE" },
  { symbol: "WSM", name: "Williams-Sonoma Inc.", exchange: "NYSE" },
  { symbol: "WST", name: "West Pharmaceutical Services Inc.", exchange: "NYSE" },
  { symbol: "WTW", name: "Willis Towers Watson PLC", exchange: "NASDAQ" },
  { symbol: "XEL", name: "Xcel Energy Inc.", exchange: "NASDAQ" },
  { symbol: "XOM", name: "Exxon Mobil Corp.", exchange: "NYSE" },
  { symbol: "XYL", name: "Xylem Inc.", exchange: "NYSE" },
  { symbol: "YUM", name: "Yum! Brands Inc.", exchange: "NYSE" },
  { symbol: "ZBRA", name: "Zebra Technologies Corp.", exchange: "NASDAQ" },
  { symbol: "ZBH", name: "Zimmer Biomet Holdings Inc.", exchange: "NYSE" },
  { symbol: "ZION", name: "Zions Bancorp N.A.", exchange: "NASDAQ" },
  { symbol: "ZTS", name: "Zoetis Inc.", exchange: "NYSE" },

  // Biotech/Pharma
  { symbol: "EXAS", name: "Exact Sciences Corp.", exchange: "NASDAQ" },
  { symbol: "NBIX", name: "Neurocrine Biosciences Inc.", exchange: "NASDAQ" },
  { symbol: "UTHR", name: "United Therapeutics Corp.", exchange: "NASDAQ" },
  { symbol: "BGNE", name: "BeiGene Ltd.", exchange: "NASDAQ" },
  { symbol: "IONS", name: "Ionis Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "BPMC", name: "Blueprint Medicines Corp.", exchange: "NASDAQ" },
  { symbol: "SRPT", name: "Sarepta Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "MEDP", name: "Medpace Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "CRSP", name: "CRISPR Therapeutics AG", exchange: "NASDAQ" },
  { symbol: "NTLA", name: "Intellia Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "RARE", name: "Ultragenyx Pharmaceutical Inc.", exchange: "NASDAQ" },
  { symbol: "ACAD", name: "ACADIA Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "MDGL", name: "Madrigal Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "PTCT", name: "PTC Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "AXSM", name: "Axsome Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "APLS", name: "Apellis Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "CYTK", name: "Cytokinetics Inc.", exchange: "NASDAQ" },
  { symbol: "DNLI", name: "Denali Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "ALKS", name: "Alkermes PLC", exchange: "NASDAQ" },
  { symbol: "ITCI", name: "Intra-Cellular Therapies Inc.", exchange: "NASDAQ" },
  { symbol: "KRYS", name: "Krystal Biotech Inc.", exchange: "NASDAQ" },
  { symbol: "INSM", name: "Insmed Inc.", exchange: "NASDAQ" },
  { symbol: "KURA", name: "Kura Oncology Inc.", exchange: "NASDAQ" },
  { symbol: "ARVN", name: "Arvinas Inc.", exchange: "NASDAQ" },
  { symbol: "SNDX", name: "Syndax Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "KYMR", name: "Kymera Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "RXRX", name: "Recursion Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "RCKT", name: "Rocket Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "MIRM", name: "Mirum Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "COGT", name: "Cogent Biosciences Inc.", exchange: "NASDAQ" },

  // More Mid-Cap Stocks
  { symbol: "ACM", name: "AECOM", exchange: "NYSE" },
  { symbol: "AIT", name: "Applied Industrial Technologies Inc.", exchange: "NYSE" },
  { symbol: "AOS", name: "A.O. Smith Corp.", exchange: "NYSE" },
  { symbol: "APPF", name: "AppFolio Inc.", exchange: "NASDAQ" },
  { symbol: "ARMK", name: "Aramark", exchange: "NYSE" },
  { symbol: "ASGN", name: "ASGN Inc.", exchange: "NYSE" },
  { symbol: "ASO", name: "Academy Sports + Outdoors Inc.", exchange: "NASDAQ" },
  { symbol: "AVAV", name: "AeroVironment Inc.", exchange: "NASDAQ" },
  { symbol: "AXON", name: "Axon Enterprise Inc.", exchange: "NASDAQ" },
  { symbol: "BJ", name: "BJ's Wholesale Club Holdings Inc.", exchange: "NYSE" },
  { symbol: "BLDR", name: "Builders FirstSource Inc.", exchange: "NYSE" },
  { symbol: "BR", name: "Broadridge Financial Solutions Inc.", exchange: "NYSE" },
  { symbol: "BRKR", name: "Bruker Corp.", exchange: "NASDAQ" },
  { symbol: "BRO", name: "Brown & Brown Inc.", exchange: "NYSE" },
  { symbol: "BURL", name: "Burlington Stores Inc.", exchange: "NYSE" },
  { symbol: "BWXT", name: "BWX Technologies Inc.", exchange: "NYSE" },
  { symbol: "CACI", name: "CACI International Inc.", exchange: "NYSE" },
  { symbol: "CASY", name: "Casey's General Stores Inc.", exchange: "NASDAQ" },
  { symbol: "CART", name: "Maplebear Inc. (Instacart)", exchange: "NASDAQ" },
  { symbol: "CDW", name: "CDW Corp.", exchange: "NASDAQ" },
  { symbol: "CELH", name: "Celsius Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "CHDN", name: "Churchill Downs Inc.", exchange: "NASDAQ" },
  { symbol: "CHE", name: "Chemed Corp.", exchange: "NYSE" },
  { symbol: "CHK", name: "Chesapeake Energy Corp.", exchange: "NASDAQ" },
  { symbol: "CHRD", name: "Chord Energy Corp.", exchange: "NASDAQ" },
  { symbol: "CHX", name: "ChampionX Corp.", exchange: "NASDAQ" },
  { symbol: "CIEN", name: "Ciena Corp.", exchange: "NYSE" },
  { symbol: "CLF", name: "Cleveland-Cliffs Inc.", exchange: "NYSE" },
  { symbol: "CLH", name: "Clean Harbors Inc.", exchange: "NYSE" },
  { symbol: "COHR", name: "Coherent Corp.", exchange: "NYSE" },
  { symbol: "COLM", name: "Columbia Sportswear Co.", exchange: "NASDAQ" },
  { symbol: "COTY", name: "Coty Inc.", exchange: "NYSE" },
  { symbol: "CR", name: "Crane Co.", exchange: "NYSE" },
  { symbol: "DAR", name: "Darling Ingredients Inc.", exchange: "NYSE" },
  { symbol: "DASH", name: "DoorDash Inc.", exchange: "NASDAQ" },
  { symbol: "DBX", name: "Dropbox Inc.", exchange: "NASDAQ" },
  { symbol: "DCI", name: "Donaldson Co. Inc.", exchange: "NYSE" },
  { symbol: "DT", name: "Dynatrace Inc.", exchange: "NYSE" },
  { symbol: "DUOL", name: "Duolingo Inc.", exchange: "NASDAQ" },
  { symbol: "EAT", name: "Brinker International Inc.", exchange: "NYSE" },
  { symbol: "EHC", name: "Encompass Health Corp.", exchange: "NYSE" },
  { symbol: "ELF", name: "e.l.f. Beauty Inc.", exchange: "NYSE" },
  { symbol: "EME", name: "EMCOR Group Inc.", exchange: "NYSE" },
  { symbol: "ENB", name: "Enbridge Inc.", exchange: "NYSE" },
  { symbol: "ENTG", name: "Entegris Inc.", exchange: "NASDAQ" },
  { symbol: "EQH", name: "Equitable Holdings Inc.", exchange: "NYSE" },
  { symbol: "EQT", name: "EQT Corp.", exchange: "NYSE" },
  { symbol: "ESTC", name: "Elastic N.V.", exchange: "NYSE" },
  { symbol: "ET", name: "Energy Transfer LP", exchange: "NYSE" },
  { symbol: "FLR", name: "Fluor Corp.", exchange: "NYSE" },
  { symbol: "FLT", name: "Fleetcor Technologies Inc.", exchange: "NYSE" },
  { symbol: "FND", name: "Floor & Decor Holdings Inc.", exchange: "NYSE" },
  { symbol: "FNF", name: "Fidelity National Financial Inc.", exchange: "NYSE" },
  { symbol: "FNV", name: "Franco-Nevada Corp.", exchange: "NYSE" },
  { symbol: "GDDY", name: "GoDaddy Inc.", exchange: "NYSE" },
  { symbol: "GEV", name: "GE Vernova Inc.", exchange: "NYSE" },
  { symbol: "GLOB", name: "Globant S.A.", exchange: "NYSE" },
  { symbol: "GMED", name: "Globus Medical Inc.", exchange: "NYSE" },
  { symbol: "GME", name: "GameStop Corp.", exchange: "NYSE" },
  { symbol: "H", name: "Hyatt Hotels Corp.", exchange: "NYSE" },
  { symbol: "HLN", name: "Haleon PLC", exchange: "NYSE" },
  { symbol: "HOOD", name: "Robinhood Markets Inc.", exchange: "NASDAQ" },
  { symbol: "HUBS", name: "HubSpot Inc.", exchange: "NYSE" },
  { symbol: "JLL", name: "Jones Lang LaSalle Inc.", exchange: "NYSE" },
  { symbol: "KVUE", name: "Kenvue Inc.", exchange: "NYSE" },
  { symbol: "LAD", name: "Lithia Motors Inc.", exchange: "NYSE" },
  { symbol: "LAMR", name: "Lamar Advertising Co.", exchange: "NASDAQ" },
  { symbol: "LNG", name: "Cheniere Energy Inc.", exchange: "NYSE" },
  { symbol: "LPLA", name: "LPL Financial Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "LPX", name: "Louisiana-Pacific Corp.", exchange: "NYSE" },
  { symbol: "LW", name: "Lamb Weston Holdings Inc.", exchange: "NYSE" },
  { symbol: "MANH", name: "Manhattan Associates Inc.", exchange: "NASDAQ" },
  { symbol: "MAT", name: "Mattel Inc.", exchange: "NASDAQ" },
  { symbol: "MORN", name: "Morningstar Inc.", exchange: "NASDAQ" },
  { symbol: "NOV", name: "Nov Inc.", exchange: "NYSE" },
  { symbol: "OLLI", name: "Ollie's Bargain Outlet Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "ONON", name: "On Holding AG", exchange: "NYSE" },
  { symbol: "OVV", name: "Ovintiv Inc.", exchange: "NYSE" },
  { symbol: "PAA", name: "Plains All American Pipeline L.P.", exchange: "NASDAQ" },
  { symbol: "PATH", name: "UiPath Inc.", exchange: "NYSE" },
  { symbol: "PCOR", name: "Procore Technologies Inc.", exchange: "NYSE" },
  { symbol: "PCTY", name: "Paylocity Holding Corp.", exchange: "NASDAQ" },
  { symbol: "RBA", name: "RB Global Inc.", exchange: "NYSE" },
  { symbol: "RNG", name: "RingCentral Inc.", exchange: "NYSE" },
  { symbol: "RRC", name: "Range Resources Corp.", exchange: "NYSE" },
  { symbol: "RVLV", name: "Revolve Group Inc.", exchange: "NYSE" },
  { symbol: "SAIA", name: "Saia Inc.", exchange: "NASDAQ" },
  { symbol: "SF", name: "Stifel Financial Corp.", exchange: "NYSE" },
  { symbol: "SIG", name: "Signet Jewelers Ltd.", exchange: "NYSE" },
  { symbol: "SITE", name: "SiteOne Landscape Supply Inc.", exchange: "NYSE" },
  { symbol: "SNX", name: "TD SYNNEX Corp.", exchange: "NYSE" },
  { symbol: "SPB", name: "Spectrum Brands Holdings Inc.", exchange: "NYSE" },
  { symbol: "SSD", name: "Simpson Manufacturing Co. Inc.", exchange: "NYSE" },
  { symbol: "TKO", name: "TKO Group Holdings Inc.", exchange: "NYSE" },
  { symbol: "TNDM", name: "Tandem Diabetes Care Inc.", exchange: "NASDAQ" },
  { symbol: "TOST", name: "Toast Inc.", exchange: "NYSE" },
  { symbol: "TTC", name: "The Toro Co.", exchange: "NYSE" },
  { symbol: "TW", name: "Tradeweb Markets Inc.", exchange: "NASDAQ" },
  { symbol: "U", name: "Unity Software Inc.", exchange: "NYSE" },
  { symbol: "UAA", name: "Under Armour Inc.", exchange: "NYSE" },
  { symbol: "VNO", name: "Vornado Realty Trust", exchange: "NYSE" },
  { symbol: "VVV", name: "Valvoline Inc.", exchange: "NYSE" },
  { symbol: "WAL", name: "Western Alliance Bancorp", exchange: "NYSE" },
  { symbol: "WBS", name: "Webster Financial Corp.", exchange: "NYSE" },
  { symbol: "WEX", name: "WEX Inc.", exchange: "NYSE" },
  { symbol: "WFRD", name: "Weatherford International PLC", exchange: "NASDAQ" },
  { symbol: "WSC", name: "WillScot Mobile Mini Holdings Corp.", exchange: "NASDAQ" },
  { symbol: "WU", name: "The Western Union Co.", exchange: "NYSE" },
  { symbol: "WWW", name: "Wolverine World Wide Inc.", exchange: "NYSE" },
  { symbol: "X", name: "United States Steel Corp.", exchange: "NYSE" },
  { symbol: "YETI", name: "YETI Holdings Inc.", exchange: "NYSE" },

  // International ADRs
  { symbol: "NVS", name: "Novartis AG", exchange: "NYSE" },
  { symbol: "AZN", name: "AstraZeneca PLC", exchange: "NASDAQ" },
  { symbol: "DEO", name: "Diageo PLC", exchange: "NYSE" },
  { symbol: "UL", name: "Unilever PLC", exchange: "NYSE" },
  { symbol: "BTI", name: "British American Tobacco PLC", exchange: "NYSE" },
  { symbol: "SNY", name: "Sanofi", exchange: "NASDAQ" },
  { symbol: "GSK", name: "GSK PLC", exchange: "NYSE" },
  { symbol: "MT", name: "ArcelorMittal S.A.", exchange: "NYSE" },
  { symbol: "ING", name: "ING Groep N.V.", exchange: "NYSE" },
  { symbol: "CX", name: "Cemex S.A.B. de C.V.", exchange: "NYSE" },
  { symbol: "ABEV", name: "Ambev S.A.", exchange: "NYSE" },
  { symbol: "AMX", name: "America Movil S.A.B. de C.V.", exchange: "NYSE" },
  { symbol: "FMX", name: "Fomento Economico Mexicano S.A.B. de C.V.", exchange: "NYSE" },
  { symbol: "KOF", name: "Coca-Cola FEMSA S.A.B. de C.V.", exchange: "NYSE" },
  { symbol: "ERJ", name: "Embraer S.A.", exchange: "NYSE" },

  // More ETFs
  { symbol: "EEM", name: "iShares MSCI Emerging Markets ETF", exchange: "NYSE" },
  { symbol: "EFA", name: "iShares MSCI EAFE ETF", exchange: "NYSE" },
  { symbol: "TIP", name: "iShares TIPS Bond ETF", exchange: "NYSE" },
  { symbol: "MUB", name: "iShares National Muni Bond ETF", exchange: "NYSE" },
  { symbol: "XHB", name: "SPDR S&P Homebuilders ETF", exchange: "NYSE" },
  { symbol: "KRE", name: "SPDR S&P Regional Banking ETF", exchange: "NYSE" },
  { symbol: "XBI", name: "SPDR S&P Biotech ETF", exchange: "NYSE" },
  { symbol: "IBB", name: "iShares Biotechnology ETF", exchange: "NASDAQ" },
  { symbol: "SMH", name: "VanEck Semiconductor ETF", exchange: "NASDAQ" },
  { symbol: "ARKK", name: "ARK Innovation ETF", exchange: "NYSE" },
  { symbol: "ARKG", name: "ARK Genomic Revolution ETF", exchange: "NYSE" },
  { symbol: "ARKQ", name: "ARK Autonomous Technology & Robotics ETF", exchange: "NYSE" },
  { symbol: "VUG", name: "Vanguard Growth ETF", exchange: "NYSE" },
  { symbol: "VTV", name: "Vanguard Value ETF", exchange: "NYSE" },
  { symbol: "VB", name: "Vanguard Small-Cap ETF", exchange: "NYSE" },
  { symbol: "VO", name: "Vanguard Mid-Cap ETF", exchange: "NYSE" },
  { symbol: "BNDX", name: "Vanguard Total International Bond ETF", exchange: "NYSE" },
  { symbol: "VCIT", name: "Vanguard Intermediate-Term Corporate Bond ETF", exchange: "NASDAQ" },
  { symbol: "SCHD", name: "Schwab U.S. Dividend Equity ETF", exchange: "NYSE" },
  { symbol: "IJR", name: "iShares Core S&P Small-Cap ETF", exchange: "NYSE" },
  { symbol: "SPYG", name: "SPDR Portfolio S&P 500 Growth ETF", exchange: "NYSE" },
  { symbol: "SPYV", name: "SPDR Portfolio S&P 500 Value ETF", exchange: "NYSE" },
  { symbol: "SPLG", name: "SPDR Portfolio S&P 500 ETF", exchange: "NYSE" },
  { symbol: "QQQM", name: "Invesco NASDAQ 100 ETF", exchange: "NASDAQ" },
  { symbol: "SOXX", name: "iShares Semiconductor ETF", exchange: "NASDAQ" },
  { symbol: "XRT", name: "SPDR S&P Retail ETF", exchange: "NYSE" },
  { symbol: "GDX", name: "VanEck Gold Miners ETF", exchange: "NYSE" },
  { symbol: "FXI", name: "iShares China Large-Cap ETF", exchange: "NYSE" },
  { symbol: "KWEB", name: "KraneShares CSI China Internet ETF", exchange: "NYSE" },
  { symbol: "UNG", name: "United States Natural Gas Fund", exchange: "NYSE" },
  { symbol: "PAVE", name: "Global X U.S. Infrastructure Development ETF", exchange: "NASDAQ" },
  { symbol: "IGV", name: "iShares Expanded Tech-Software ETF", exchange: "NASDAQ" },
  { symbol: "ITA", name: "iShares U.S. Aerospace & Defense ETF", exchange: "NYSE" },
  { symbol: "VIG", name: "Vanguard Dividend Appreciation ETF", exchange: "NYSE" },
  { symbol: "JEPI", name: "JPMorgan Equity Premium Income ETF", exchange: "NYSE" },

  // More REITs
  { symbol: "O", name: "Realty Income Corp.", exchange: "NYSE" },
  { symbol: "WPC", name: "W.P. Carey Inc.", exchange: "NYSE" },
  { symbol: "STAG", name: "STAG Industrial Inc.", exchange: "NYSE" },
  { symbol: "FR", name: "First Industrial Realty Trust Inc.", exchange: "NYSE" },
  { symbol: "BRX", name: "Brixmor Property Group Inc.", exchange: "NYSE" },
  { symbol: "KRG", name: "Kite Realty Group Trust", exchange: "NYSE" },
  { symbol: "SUI", name: "Sun Communities Inc.", exchange: "NYSE" },
  { symbol: "ELS", name: "Equity LifeStyle Properties Inc.", exchange: "NYSE" },
  { symbol: "OHI", name: "Omega Healthcare Investors Inc.", exchange: "NYSE" },
  { symbol: "MPW", name: "Medical Properties Trust Inc.", exchange: "NYSE" },
  { symbol: "DOC", name: "Healthpeak Properties Inc.", exchange: "NYSE" },
  { symbol: "CTRE", name: "CareTrust REIT Inc.", exchange: "NYSE" },
  { symbol: "NNN", name: "NNN REIT Inc.", exchange: "NYSE" },
  { symbol: "MAC", name: "The Macerich Co.", exchange: "NYSE" },
  { symbol: "SKT", name: "Tanger Inc.", exchange: "NYSE" },
  { symbol: "WY", name: "Weyerhaeuser Co.", exchange: "NYSE" },
  { symbol: "CUZ", name: "Cousins Properties Inc.", exchange: "NYSE" },
  { symbol: "KRC", name: "Kilroy Realty Corp.", exchange: "NYSE" },
  { symbol: "EPR", name: "EPR Properties", exchange: "NYSE" },
  { symbol: "PEB", name: "Pebblebrook Hotel Trust", exchange: "NYSE" },
  { symbol: "HR", name: "Healthcare Realty Trust Inc.", exchange: "NYSE" },
  { symbol: "GLPI", name: "Gaming and Leisure Properties Inc.", exchange: "NASDAQ" },
  { symbol: "HIW", name: "Highwoods Properties Inc.", exchange: "NYSE" },
  { symbol: "HPP", name: "Hudson Pacific Properties Inc.", exchange: "NYSE" },
  { symbol: "JBGS", name: "JBG SMITH Properties", exchange: "NYSE" },
]
